/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerPath {
  'field' : string,
  'paths' : Array<CareerPathEntry>,
}
export interface CareerPathEntry {
  'title' : string,
  'demandLevel' : bigint,
  'certifications' : Array<string>,
  'preparationMonths' : bigint,
  'skills' : Array<string>,
}
export interface Job {
  'id' : bigint,
  'title' : string,
  'officialUrl' : string,
  'jobType' : JobType,
  'deadline' : Time,
  'summary' : string,
  'state' : State,
  'isFeatured' : boolean,
  'category' : string,
  'organization' : string,
  'salaryRange' : string,
  'skills' : Array<string>,
  'qualification' : string,
}
export interface JobFilter {
  'jobType' : [] | [JobType],
  'sortByDeadlineAsc' : boolean,
  'state' : [] | [State],
  'onlyFeatured' : boolean,
  'category' : [] | [string],
}
export type JobType = { 'govt' : null } |
  { 'priv' : null };
export interface LearningHub {
  'field' : string,
  'sections' : Array<LearningHubSection>,
}
export interface LearningHubSection {
  'title' : string,
  'resources' : Array<string>,
}
export type Preference = { 'both' : null } |
  { 'govt' : null } |
  { 'priv' : null };
export type State = string;
export type Time = bigint;
export interface UserProfile {
  'preferredState' : State,
  'year' : bigint,
  'degree' : string,
  'preference' : Preference,
  'targetRole' : string,
}
export interface _SERVICE {
  'addJob' : ActorMethod<[Job], bigint>,
  'getCareerPaths' : ActorMethod<[], Array<CareerPath>>,
  'getLearningHubs' : ActorMethod<[], Array<LearningHub>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserSavedJobs' : ActorMethod<[], [] | [Array<bigint>]>,
  'listJobs' : ActorMethod<[[] | [JobFilter]], Array<Job>>,
  'saveJob' : ActorMethod<[bigint], undefined>,
  'unsaveJob' : ActorMethod<[bigint], undefined>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];