/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobType = IDL.Variant({ 'govt' : IDL.Null, 'priv' : IDL.Null });
export const Time = IDL.Int;
export const State = IDL.Text;
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'officialUrl' : IDL.Text,
  'jobType' : JobType,
  'deadline' : Time,
  'summary' : IDL.Text,
  'state' : State,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'organization' : IDL.Text,
  'salaryRange' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'qualification' : IDL.Text,
});
export const CareerPathEntry = IDL.Record({
  'title' : IDL.Text,
  'demandLevel' : IDL.Nat,
  'certifications' : IDL.Vec(IDL.Text),
  'preparationMonths' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
});
export const CareerPath = IDL.Record({
  'field' : IDL.Text,
  'paths' : IDL.Vec(CareerPathEntry),
});
export const LearningHubSection = IDL.Record({
  'title' : IDL.Text,
  'resources' : IDL.Vec(IDL.Text),
});
export const LearningHub = IDL.Record({
  'field' : IDL.Text,
  'sections' : IDL.Vec(LearningHubSection),
});
export const Preference = IDL.Variant({
  'both' : IDL.Null,
  'govt' : IDL.Null,
  'priv' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'preferredState' : State,
  'year' : IDL.Nat,
  'degree' : IDL.Text,
  'preference' : Preference,
  'targetRole' : IDL.Text,
});
export const JobFilter = IDL.Record({
  'jobType' : IDL.Opt(JobType),
  'sortByDeadlineAsc' : IDL.Bool,
  'state' : IDL.Opt(State),
  'onlyFeatured' : IDL.Bool,
  'category' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addJob' : IDL.Func([Job], [IDL.Nat], []),
  'getCareerPaths' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
  'getLearningHubs' : IDL.Func([], [IDL.Vec(LearningHub)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserSavedJobs' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Nat))], ['query']),
  'listJobs' : IDL.Func([IDL.Opt(JobFilter)], [IDL.Vec(Job)], ['query']),
  'saveJob' : IDL.Func([IDL.Nat], [], []),
  'unsaveJob' : IDL.Func([IDL.Nat], [], []),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobType = IDL.Variant({ 'govt' : IDL.Null, 'priv' : IDL.Null });
  const Time = IDL.Int;
  const State = IDL.Text;
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'officialUrl' : IDL.Text,
    'jobType' : JobType,
    'deadline' : Time,
    'summary' : IDL.Text,
    'state' : State,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'organization' : IDL.Text,
    'salaryRange' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'qualification' : IDL.Text,
  });
  const CareerPathEntry = IDL.Record({
    'title' : IDL.Text,
    'demandLevel' : IDL.Nat,
    'certifications' : IDL.Vec(IDL.Text),
    'preparationMonths' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
  });
  const CareerPath = IDL.Record({
    'field' : IDL.Text,
    'paths' : IDL.Vec(CareerPathEntry),
  });
  const LearningHubSection = IDL.Record({
    'title' : IDL.Text,
    'resources' : IDL.Vec(IDL.Text),
  });
  const LearningHub = IDL.Record({
    'field' : IDL.Text,
    'sections' : IDL.Vec(LearningHubSection),
  });
  const Preference = IDL.Variant({
    'both' : IDL.Null,
    'govt' : IDL.Null,
    'priv' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'preferredState' : State,
    'year' : IDL.Nat,
    'degree' : IDL.Text,
    'preference' : Preference,
    'targetRole' : IDL.Text,
  });
  const JobFilter = IDL.Record({
    'jobType' : IDL.Opt(JobType),
    'sortByDeadlineAsc' : IDL.Bool,
    'state' : IDL.Opt(State),
    'onlyFeatured' : IDL.Bool,
    'category' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addJob' : IDL.Func([Job], [IDL.Nat], []),
    'getCareerPaths' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
    'getLearningHubs' : IDL.Func([], [IDL.Vec(LearningHub)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserSavedJobs' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Nat))], ['query']),
    'listJobs' : IDL.Func([IDL.Opt(JobFilter)], [IDL.Vec(Job)], ['query']),
    'saveJob' : IDL.Func([IDL.Nat], [], []),
    'unsaveJob' : IDL.Func([IDL.Nat], [], []),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };