/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CareerPathEntry {
    title: string;
    demandLevel: bigint;
    certifications: Array<string>;
    preparationMonths: bigint;
    skills: Array<string>;
}
export interface Job {
    id: bigint;
    title: string;
    officialUrl: string;
    jobType: JobType;
    deadline: Time;
    summary: string;
    state: State;
    isFeatured: boolean;
    category: string;
    organization: string;
    salaryRange: string;
    skills: Array<string>;
    qualification: string;
}
export type Time = bigint;
export interface JobFilter {
    jobType?: JobType;
    sortByDeadlineAsc: boolean;
    state?: State;
    onlyFeatured: boolean;
    category?: string;
}
export interface CareerPath {
    field: string;
    paths: Array<CareerPathEntry>;
}
export interface LearningHubSection {
    title: string;
    resources: Array<string>;
}
export interface LearningHub {
    field: string;
    sections: Array<LearningHubSection>;
}
export type State = string;
export interface UserProfile {
    preferredState: State;
    year: bigint;
    degree: string;
    preference: Preference;
    targetRole: string;
}
export enum JobType {
    govt = "govt",
    priv = "priv"
}
export enum Preference {
    both = "both",
    govt = "govt",
    priv = "priv"
}
export interface backendInterface {
    addJob(job: Job): Promise<bigint>;
    getCareerPaths(): Promise<Array<CareerPath>>;
    getLearningHubs(): Promise<Array<LearningHub>>;
    getUserProfile(): Promise<UserProfile | null>;
    getUserSavedJobs(): Promise<Array<bigint> | null>;
    listJobs(filter: JobFilter | null): Promise<Array<Job>>;
    saveJob(jobId: bigint): Promise<void>;
    unsaveJob(jobId: bigint): Promise<void>;
    updateUserProfile(profile: UserProfile): Promise<void>;
}
import type { Job as _Job, JobFilter as _JobFilter, JobType as _JobType, Preference as _Preference, State as _State, Time as _Time, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addJob(arg0: Job): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(to_candid_Job_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(to_candid_Job_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCareerPaths(): Promise<Array<CareerPath>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareerPaths();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareerPaths();
            return result;
        }
    }
    async getLearningHubs(): Promise<Array<LearningHub>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLearningHubs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLearningHubs();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSavedJobs(): Promise<Array<bigint> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSavedJobs();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSavedJobs();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listJobs(arg0: JobFilter | null): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobs(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobs(to_candid_opt_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveJob(arg0);
            return result;
        }
    }
    async unsaveJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveJob(arg0);
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_JobType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Preference_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Preference): Preference {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<bigint>]): Array<bigint> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    officialUrl: string;
    jobType: _JobType;
    deadline: _Time;
    summary: string;
    state: _State;
    isFeatured: boolean;
    category: string;
    organization: string;
    salaryRange: string;
    skills: Array<string>;
    qualification: string;
}): {
    id: bigint;
    title: string;
    officialUrl: string;
    jobType: JobType;
    deadline: Time;
    summary: string;
    state: State;
    isFeatured: boolean;
    category: string;
    organization: string;
    salaryRange: string;
    skills: Array<string>;
    qualification: string;
} {
    return {
        id: value.id,
        title: value.title,
        officialUrl: value.officialUrl,
        jobType: from_candid_JobType_n17(_uploadFile, _downloadFile, value.jobType),
        deadline: value.deadline,
        summary: value.summary,
        state: value.state,
        isFeatured: value.isFeatured,
        category: value.category,
        organization: value.organization,
        salaryRange: value.salaryRange,
        skills: value.skills,
        qualification: value.qualification
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredState: _State;
    year: bigint;
    degree: string;
    preference: _Preference;
    targetRole: string;
}): {
    preferredState: State;
    year: bigint;
    degree: string;
    preference: Preference;
    targetRole: string;
} {
    return {
        preferredState: value.preferredState,
        year: value.year,
        degree: value.degree,
        preference: from_candid_Preference_n8(_uploadFile, _downloadFile, value.preference),
        targetRole: value.targetRole
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    govt: null;
} | {
    priv: null;
}): JobType {
    return "govt" in value ? JobType.govt : "priv" in value ? JobType.priv : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    both: null;
} | {
    govt: null;
} | {
    priv: null;
}): Preference {
    return "both" in value ? Preference.both : "govt" in value ? Preference.govt : "priv" in value ? Preference.priv : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n15(_uploadFile, _downloadFile, x));
}
function to_candid_JobFilter_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobFilter): _JobFilter {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Job_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Job): _Job {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Preference_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Preference): _Preference {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobFilter | null): [] | [_JobFilter] {
    return value === null ? candid_none() : candid_some(to_candid_JobFilter_n12(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jobType?: JobType;
    sortByDeadlineAsc: boolean;
    state?: State;
    onlyFeatured: boolean;
    category?: string;
}): {
    jobType: [] | [_JobType];
    sortByDeadlineAsc: boolean;
    state: [] | [_State];
    onlyFeatured: boolean;
    category: [] | [string];
} {
    return {
        jobType: value.jobType ? candid_some(to_candid_JobType_n3(_uploadFile, _downloadFile, value.jobType)) : candid_none(),
        sortByDeadlineAsc: value.sortByDeadlineAsc,
        state: value.state ? candid_some(value.state) : candid_none(),
        onlyFeatured: value.onlyFeatured,
        category: value.category ? candid_some(value.category) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    officialUrl: string;
    jobType: JobType;
    deadline: Time;
    summary: string;
    state: State;
    isFeatured: boolean;
    category: string;
    organization: string;
    salaryRange: string;
    skills: Array<string>;
    qualification: string;
}): {
    id: bigint;
    title: string;
    officialUrl: string;
    jobType: _JobType;
    deadline: _Time;
    summary: string;
    state: _State;
    isFeatured: boolean;
    category: string;
    organization: string;
    salaryRange: string;
    skills: Array<string>;
    qualification: string;
} {
    return {
        id: value.id,
        title: value.title,
        officialUrl: value.officialUrl,
        jobType: to_candid_JobType_n3(_uploadFile, _downloadFile, value.jobType),
        deadline: value.deadline,
        summary: value.summary,
        state: value.state,
        isFeatured: value.isFeatured,
        category: value.category,
        organization: value.organization,
        salaryRange: value.salaryRange,
        skills: value.skills,
        qualification: value.qualification
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredState: State;
    year: bigint;
    degree: string;
    preference: Preference;
    targetRole: string;
}): {
    preferredState: _State;
    year: bigint;
    degree: string;
    preference: _Preference;
    targetRole: string;
} {
    return {
        preferredState: value.preferredState,
        year: value.year,
        degree: value.degree,
        preference: to_candid_Preference_n21(_uploadFile, _downloadFile, value.preference),
        targetRole: value.targetRole
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Preference): {
    both: null;
} | {
    govt: null;
} | {
    priv: null;
} {
    return value == Preference.both ? {
        both: null
    } : value == Preference.govt ? {
        govt: null
    } : value == Preference.priv ? {
        priv: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    govt: null;
} | {
    priv: null;
} {
    return value == JobType.govt ? {
        govt: null
    } : value == JobType.priv ? {
        priv: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
